### ISSUE TITLE
jetson_stats_prometheus_collector.py fails with error on line 54

### ISSUE THREAD

**Issue by rstranscore** [svcavallar/jetson-stats-grafana-dashboard#4]
System is running Ubuntu server LTS 18.04 with python 3.6 and running jtop from jetston_stats I do get a working jtop.

I went as far as adding a debug print in there to dump what is being pulled up and my initial review didnt spot anything missing but python isnt a strong point and the Xavier unit is a custom which may be adding to the confusion.

Debug: self._jetson.board = {'hardware': {'Model': 'Transport XCB', '699-level Part Number': '699-82888-0004-400 G.0', 'P-Number': 'p2888-0004', 'Module': 'NVIDIA Jetson AGX Xavier (32 GB ram)', 'SoC': 'tegra194', 'CUDA Arch BIN': '7.2', 'Serial Number': '0420319084239', 'L4T': '32.5.1', 'Jetpack': '4.5.1'}, 
                             'platform': {'Machine': 'aarch64', 'System': 'Linux', 'Distribution': 'Ubuntu 18.04 Bionic Beaver', 'Release': '4.9.201-32.5.0_C01571-19S00A00.001.img+e443483e8c+ge443483e8c9c', 'Python': '3.6.9'}, 
                             'libraries': {'CUDA': '10.2.89', 'OpenCV': '4.1.1', 'OpenCV-Cuda': False, 'cuDNN': '8.0.0.180', 'TensorRT': '7.1.3.0', 'VPI': '1.0.15', 'Vulkan': '1.2.70'}}
                             
Error being seen is as follows

Traceback (most recent call last):
  File "./jetson_stats_prometheus_collector.py", line 192, in <module>
    REGISTRY.register(CustomCollector())
  File "/usr/local/lib/python3.6/dist-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.6/dist-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "./jetson_stats_prometheus_collector.py", line 54 in collect
    'Machine': self._jetson.board['info']['machine'],
KeyError: 'info'
Closing jetson-stats connection...

**Comment by djemeljanovs** [comment]
Same issue observed

**Comment by Kanan99** [comment]
I'm dealing with the same problem.

**Comment by xiafengdongzhi** [comment]
Same issue observed

**Comment by xiafengdongzhi** [comment]
Can anyone help us, please?

**Comment by Kanan99** [comment]
@xiafengdongzhi another alternative is to use Jetson Orin 

https://docs.nvidia.com/moj/setup/quick-start.html

**Comment by xiafengdongzhi** [comment]
> @xiafengdongzhi another alternative is to use Jetson Orin
> 
> https://docs.nvidia.com/moj/setup/quick-start.html

Thank you very much for your reply, but we currently require tx2 to be used.

**Comment by Kanan99** [comment]
@xiafengdongzhi 

We'd write our node exporters for any companion other than ORINs. I'd be happy if you have any samples or references to start for that.

**Comment by LucasJSch** [comment]
```bash
self._jetson = jtop()
json = self._jetson.json()
```

`json` contains all the data. Its structure apparently varies according to the version of `jtop`. I'd recommend print this JSON and adapt to specific needs.

**Comment by TheHunterDog** [comment]
I changed the code to work with a Jetson Nano and opened a [PR](https://github.com/svcavallar/jetson-stats-grafana-dashboard/pull/5) if you didn't resolve the issues yourself feel free to use the updated code
